# Generated by Django 5.1.1 on 2024-10-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
