# Generated by Django 5.1.1 on 2024-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_etudiants_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
